# Importing the packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress =True, linewidth =100, precision = 2)

Importing the Data

In [3]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header =1, autostrip = True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for incomplete Data

In [4]:
np.isnan(raw_data_np).sum()

88005

In [5]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis = 0)

C:\Users\EE User\AppData\Local\Temp\ipykernel_14384\3983241459.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


In [6]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),temporary_mean, np.nanmax(raw_data_np, axis = 0)])

C:\Users\EE User\AppData\Local\Temp\ipykernel_14384\3321554586.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),temporary_mean, np.nanmax(raw_data_np, axis = 0)])


In [8]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset 

# ##splitting the coloumns

In [9]:
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [10]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

## Re-importing the dataset

In [21]:
loan_data_strings = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';',
                                  skip_header =1, 
                                  autostrip = True,
                                 usecols = columns_strings,
                                 dtype = str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [22]:
loan_data_numeric = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';',
                                  skip_header =1, 
                                  autostrip = True,
                                 usecols = columns_numeric,
                                 filling_values = temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

## The Name of the coloumns

In [23]:
header_full = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';', 
                                  autostrip = True,
                                 skip_footer = raw_data_np.shape[0],
                                 dtype = str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [24]:
header_strings,header_numeric = header_full[columns_strings],header_full[columns_numeric]

In [25]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [26]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Creating checkpoints:

Places throughout our code where we store a copy of our dataset(or only parts of it)
we want to avoid losing a lot of progress
aaaaaaaan extremly reliable practice when we need to clean or preprocess many parts of a dataset.

In [27]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return (checkpoint_variable)

In [28]:
checkpoint_test = checkpoint("checkpoint_test", header_strings, loan_data_strings)

In [29]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [30]:
np.array_equal(checkpoint_test['data'],loan_data_strings)

True

# Manipulating string Columns

In [31]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [32]:
header_strings[0]= "issue_date"

In [33]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

##issue Date

In [34]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

values are arranged in alphabetical order, rather than chronologically

In [35]:
np.chararray.strip(loan_data_strings[:,0],"-15")

chararray(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

The strip function doesn;t automattically remove these values we need to overwrite as below

In [36]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],"-15")

## In Analysis
represent month values as integers
store the data using less memory (space)
a more easy to follow order of the months

In [37]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [38]:
months = np.array([' ','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])


In [39]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0]== months[i],
                                     i,
                                     loan_data_strings[:,0])

In [40]:
np.unique(loan_data_strings[:,0])

array(['', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

Loan Status

In [41]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [42]:
loan_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [43]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [44]:
np.unique(loan_data_strings[:,1]).size

9

We can use np.where()to assign a different number to each one. However, Regression only care if the candidate is in a stable financial condition
we need to split all possible values into either group("good" vs"bad")1, 0 for good nd bad

In [45]:
status_bad = np.array([' ','charged off','Default','Late (31-120 days)'])

In [46]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)

In [47]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

# Term

In [48]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [49]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [50]:
loan_data_strings[:,2]= np.chararray.strip(loan_data_strings[:,2], " months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

when we have missing data in CRM , we assume the worst  ie, 60 months(5 years) is the worst case here. so replace the missing value with 60

In [51]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                 '60',loan_data_strings[:,2])

In [52]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

# Grade and Subgrade

In [53]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [54]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [55]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

Filling Sub GrADE

In [56]:
for i in np.unique(loan_data_strings[:,3])[1,:]:
    loan_data_strings[:,4]= np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                    i + '5',
                                    loan_data_strings[:,4])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [57]:
np.unique(loan_data_strings[:,4],return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

In [58]:
 loan_data_strings[:,4]= np.where((loan_data_strings[:,4] == ''),
                                    'H1',
                                    loan_data_strings[:,4])

In [59]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

we no longer have any misssing value as it is replaced by H1 now we can remove the grade coloumn 

# Removing Grade

In [60]:
loan_data_strings = np.delete(loan_data_strings, 3, axis= 1)

In [61]:
loan_data_strings[:,3]


array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [62]:
header_strings = np.delete(header_strings, 3)

In [63]:
header_strings[3]

'sub_grade'

# Converting sub Grades

In [64]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [65]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] +1))
dict_sub_grade = dict(zip(keys,values))

In [66]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

Let's break down the code step by step to understand its meaning:

np.unique(loan_data_strings[:, 3]): This part of the code is using NumPy (imported as np) to extract the unique elements from the 3rd column (index 3) of the loan_data_strings array. The loan_data_strings[:, 3] notation means that we are taking all rows and only the 3rd column of the loan_data_strings array.

np.unique(loan_data_strings[:, 3]).shape[0]: After finding the unique elements in the 3rd column, shape[0] is used to get the number of unique elements. This will return an integer value representing the number of unique elements in the 3rd column of the loan_data_strings array.

range(1, np.unique(loan_data_strings[:, 3]).shape[0] + 1): The range() function is used to create a sequence of numbers starting from 1 and ending at np.unique(loan_data_strings[:, 3]).shape[0] + 1. The + 1 is used because the range() function generates numbers up to, but not including, the stop value.

In [67]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] ==i,
                                     dict_sub_grade[i],
                                     loan_data_strings[:,3])

In [68]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

# Verification status

In [69]:
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [70]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

'Source Verified' is the loan application which include investor backing

In [71]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'),0,1)

In [72]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

np.where((loan_data_strings[:, 4] == '') | (loan_data_strings[:, 4] == 'Not Verified'), 0, 1): The np.where() function is used with the boolean array from step 3 as the condition. It checks each element of the array and replaces the elements that are True with 0 and the elements that are False with 1.

# URL

In [73]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [74]:
np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [75]:
loan_data_strings[:,5] =np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [76]:
header_full


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [77]:
loan_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [78]:
loan_data_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [79]:
np.array_equal(loan_data_numeric[:,0].astype(dtype = np.int32),loan_data_strings[:,5].astype(dtype = np.int32))

True

The URL coloumn does'nt hold any addditional information we can't already extract from ID coloumn

In [80]:
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)
header_strings = np.delete(header_strings, 5)

In [81]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [82]:
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [83]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [84]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# State Address

In [85]:
header_strings

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [86]:
header_strings[5] = 'state_address'

In [87]:
np.unique(loan_data_strings[:,5]).size

50

we suspect Iowa was purposfully left as a baseline benchmark
When doing research or analysis on a variable with many categories. it is normal to pick one as a benchmark and include dummy variable for the rest.

In [88]:
states_names, states_count = np.unique(loan_data_strings[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted],states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

states_names, states_count = np.unique(loan_data_strings[:,5], return_counts = True): This line extracts the unique elements from the 5th column of the loan_data_strings array and counts their occurrences. The resulting states_names array will contain the unique state names, and the states_count array will contain the corresponding counts.

states_count_sorted = np.argsort(-states_count): The -states_count part negates the values in the states_count array to sort them in descending order. The np.argsort() function then returns the indices that would sort the array in ascending order, but since the values were negated, it effectively sorts the indices in descending order based on the counts. The resulting states_count_sorted array will have indices indicating the order in which the state counts appear in descending order.

states_names[states_count_sorted], states_count[states_count_sorted]: This line uses fancy indexing to reorder the states_names and states_count arrays based on the states_count_sorted indices. By doing so, the state names and their counts will be presented in descending order, where the state with the highest count appears first, followed by the next highest count, and so on.

So, the output of this code will be two arrays: states_names and states_count, both sorted in descending order based on the counts of occurrences of each state in the 5th column of the loan_data_strings array. The state with the highest count will be the first element in the sorted arrays.

In [89]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5]== '',
                                 0,
                                 loan_data_strings[:,5])

np.where(loan_data_strings[:, 5] == '', 0, loan_data_strings[:, 5]): This is the np.where() function used with three arguments:

The first argument loan_data_strings[:, 5] == '' creates a boolean array that is True where the elements in the 5th column are empty strings ('') and False otherwise.

The second argument 0 is the value that replaces the empty strings. So, wherever the condition loan_data_strings[:, 5] == '' is True, the corresponding element in the 5th column will be replaced with 0.

The third argument loan_data_strings[:, 5] is the value used when the condition loan_data_strings[:, 5] == '' is False. In other words, for the elements in the 5th column that are not empty strings, their original values will be kept unchanged.

Overall, this code is updating the 5th column of the loan_data_strings array in place. It converts any empty strings in that column to the integer value 0, and all other non-empty strings (if any) remain unchanged. This might be done to handle missing or empty data in the dataset, setting the missing state names to 0, possibly as a placeholder or a specific indication for missing data.



_If we assign a unique value to each state,thus allow outliers to have a big influence on the coefficients_

** We have very little data for too many states to examine each one individually.**

_The more categories a variable has, the fewer data will be available for eaacah one._

In [90]:
states_west = np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [91]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_west),1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_south),2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_midwest),3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_east),4, loan_data_strings[:,5])

In [92]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

_We have converted whatever string data we had into numeric values stored as text_

# Converting to Numbers


In [93]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [96]:
loan_data_strings = np.where(np.char.isnumeric(loan_data_strings), loan_data_strings, '0').astype(int)


In [97]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

# Check point 1: Strings

In [98]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_strings, loan_data_strings)

In [99]:
checkpoint_strings["header"]


array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [100]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [101]:
np.array_equal(checkpoint_strings['data'], loan_data_strings)

True

# Manipulating Numeric Columns

In [102]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [103]:
np.isnan(loan_data_numeric).sum()

0

# Substitute "Filler" Values

In [104]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

_There aren't any missing values in the array._

_We must substitute all those fillers with the worst possible values._

_We must check wheather any of the elements of this column equal the temporary_fill_

# ID

In [105]:
temporary_fill

68616520.0

In [106]:
np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

_temporary_fill = np.nanmax(raw_data_np) +1
temporary_mean = np.nanmean(raw_data_np,axis =0)_

In [107]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()

0

In [108]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Temporary Stats

In [109]:
temporary_stats[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

# Funded Amount

In [110]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [111]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_stats[0, columns_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [112]:
temporary_stats[0,columns_numeric[3]]

6.0

Even though we converted the values of loan_status earlier we generated temporary stats even before that.

Filling out the remaining numeric coloumns accorfing to the head of Data Analytics casting directions

# Loaned Amount, Interest Rate, Total Payment, Installment

In [113]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [114]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                      temporary_stats[2, columns_numeric[i]],
                                      loan_data_numeric[:,i])

In [115]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

**Currency Change**

*The Exchange Rate*

In [116]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [117]:
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [118]:
exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)    

exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [119]:
exchange_rate.shape

(10000,)

In [120]:
loan_data_numeric.shape

(10000, 6)

In [121]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [122]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [123]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

**From USD to EUR**

In [124]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [125]:
columns_dollar = np.array([1,2,4,5])

In [126]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [127]:
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1)

SyntaxError: incomplete input (2221160274.py, line 2)

In [128]:
loan_data_numeric.shape

(10000, 7)

In [129]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

**Expanding the header**

In [130]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [131]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [132]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [133]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [134]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [135]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [136]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [137]:
header_numeric = header_numeric[columns_index_order]

In [138]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [139]:
loan_data_numeric = loan_data_numeric[:,columns_index_order]

IndexError: index 7 is out of bounds for axis 1 with size 7

**Interest Rate**

In [140]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [141]:
loan_data_numeric[:,5]

array([9452.96, 4679.7 , 1969.83, ..., 2185.64, 3199.4 ,  301.9 ])

In [142]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [143]:
loan_data_numeric[:,5]

array([94.53, 46.8 , 19.7 , ..., 21.86, 31.99,  3.02])

**Checkpoint 2: Numeric**

In [144]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", header_numeric, loan_data_numeric)

In [145]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,       94.53,        1.1 ],
        [57693261.  ,    30000.  ,    30000.  , ...,      938.57,       46.8 ,        1.11],
        [59432726.  ,    15000.  ,    15000.  , ...,      494.86,       19.7 ,        1.13],
        ...,
        [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,       21.86,        1.12],
        [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,       31.99,        1.11],
        [66055249.  ,    10000.  ,    10000.  , ...,      309.97,        3.02,        1.09]]))

# Creating the "Complete" Dataset

In [146]:
checkpoint_strings['data'].shape

(10000, 6)

In [147]:
checkpoint_numeric['data'].shape

(10000, 7)

In [148]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [149]:
loan_data

array([[48010226.,    35000.,    35000., ...,       13.,        1.,        1.],
       [57693261.,    30000.,    30000., ...,        5.,        1.,        4.],
       [59432726.,    15000.,    15000., ...,       10.,        1.,        4.],
       ...,
       [50415990.,    10000.,    10000., ...,        5.,        1.,        1.],
       [46154151.,    35000.,    10000., ...,       17.,        1.,        3.],
       [66055249.,    10000.,    10000., ...,        4.,        0.,        3.]])

In [150]:
np.isnan(loan_data).sum()

0

In [151]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

**Sorting the New Dataset**

In [152]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [153]:
loan_data

array([[  373332.,     9950.,     1000., ...,       21.,        0.,        1.],
       [  575239.,    12000.,    12000., ...,       36.,        1.,        2.],
       [  707689.,    10000.,    10000., ...,       13.,        1.,        0.],
       ...,
       [68614880.,     5600.,     5600., ...,        8.,        1.,        1.],
       [68615915.,     4000.,     4000., ...,       10.,        1.,        2.],
       [68616519.,    21600.,    21600., ...,        3.,        0.,        2.]])

In [154]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

**Storing the New Dataset**

In [155]:
loan_data = np.vstack((header_full, loan_data))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 17 and the array at index 1 has size 13

In [156]:
np.savetxt("loan-data-preprocessed.csv", 
           loan_data, 
           fmt = '%s',
           delimiter = ',')